<a href="https://colab.research.google.com/github/rocowork/colab/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 引入 numpy 模組
import numpy as np
np1 = np.array([1, 2, 3])
np2 = np.array([3, 4, 5])

# 陣列相加
print(np1 + np2) # [4 6 8]

# 顯示相關資訊
print(np1.ndim, np1.shape, np1.dtype) # 1 (3,) int64 => 一維陣列, 三個元素, 資料型別

np3 = np.array([1, 2, 3, 4, 5, 6])

[4 6 8]
1 (3,) int64


In [11]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

print(type(np_height)) #Print out the type of np_height

# Calculate bmi
bmi = np_weight / np_height ** 2

# Print the result
print(bmi)

# For a boolean response
bmi > 23

# Print only those observations above 23
bmi[bmi > 23]



<class 'numpy.ndarray'>
[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [13]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

# Create a numpy array np_weight_kg from weight_kg
np_weight_kg = np.array(weight_kg)    

# Create np_weight_lbs from np_weight_kg
np_weight_lbs = np_weight_kg / 2.2
# Print out np_weight_lbs
print(np_weight_lbs)

[37.11363636 44.32727273 43.29545455 42.26363636 39.17272727 40.20454545]


In [27]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

# Set the index for brics
brics.index = ["BR", "RU", "IN", "CH", "SA"]

# Print out brics with new index values
print(brics)

# Print out brics column as Pandas Series
print(brics['area'])

# Print out brics column as Pandas DataFrame
print(brics[['area']])

# Print out DataFrame with country and capital columns
print(brics[['country', 'capital']])

# Print out first 4 observations
print(brics[0:4])

# Print out  third, and fourth observation
print(brics[2:4])

# Print out observation for INDIA
print(brics.iloc[2])

# Print out observations for Brazil and South Africa
print(brics.loc[['BR', 'SA']])

     area    capital       country  population
0   8.516   Brasilia        Brazil      200.40
1  17.100     Moscow        Russia      143.50
2   3.286  New Dehli         India     1252.00
3   9.597    Beijing         China     1357.00
4   1.221   Pretoria  South Africa       52.98
      area    capital       country  population
BR   8.516   Brasilia        Brazil      200.40
RU  17.100     Moscow        Russia      143.50
IN   3.286  New Dehli         India     1252.00
CH   9.597    Beijing         China     1357.00
SA   1.221   Pretoria  South Africa       52.98
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64
      area
BR   8.516
RU  17.100
IN   3.286
CH   9.597
SA   1.221
         country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Dehli
CH         China    Beijing
SA  South Africa   Pretoria
      area    capital country  population
BR   8.516   Brasilia  Brazil       200.4
RU  17.100     Mosco