<a href="https://colab.research.google.com/github/rocowork/colab/blob/master/Scikit_Learn_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Scikit-Learn dataset 資料讀入與資料探索 1. digits 2. iris

#讀入資料digits
# Import `datasets` from `sklearn`
from sklearn import datasets
# Load in the `digits` data
digits = datasets.load_digits()
# Print the `digits` data 
print(digits)


In [0]:
# Import the `pandas` library as `pd`
import pandas as pd

# Load in the data with `read_csv()`
digits = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits.tra", header=None)  #.tra 與 .tes 機器學習資料 分訓練與測試資料

# Print out `digits`
print(digits)

In [22]:
# Get the keys of the `digits` data
print("可蒐集的基本資訊:",digits.keys())                   #keys() 方法來得知有哪些基本資訊可以搜集

# Print out the data
print("觀察預測變數:",digits.data)                         #data屬性 觀察預測變數

# Print out the target values
print("觀察目標變數:",digits.target)                       #target屬性 觀察目標變數

# Print out the description of the `digits` data
print("閱讀資料的描述文件:",digits.DESCR)                  #DESCR屬性 閱讀資料的描述文件

可蒐集的基本資訊: dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])
觀察預測變數: [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
觀察目標變數: [0 1 2 ... 8 9 8]
閱讀資料的描述文件: .. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made 

In [27]:
import numpy as np
# Isolate the `digits` data
digits_data = digits.data

# Inspect the shape
print(digits_data.shape)

# Isolate the target values with `target`
digits_target = digits.target

# Inspect the shape
print(digits_target.shape)

# Print the number of unique labels
number_digits = len(np.unique(digits.target))

# Isolate the `images`
digits_images = digits.images

# Inspect the shape
print(digits_images.shape)

#檢視 digits.data.shape 可以得知資料有 1,797 個觀測值，64 個變數，檢視 digits.target.shape 可以得知資料有 1,797 個目標值（或稱標籤值），而檢視 len(np.unique(digits.target)) 可以得知所有的目標值只有 10 個相異值：0 到 9，意即我們的模型是要辨識手寫數字圖片是 0 到 9 中的哪一個數字。
#最後是 digits.images 的三個維度：1,797 個 8 x 8 像素的矩陣，我們可以進一步將 digits.images 轉換（reshape）為兩個維度，並且使用 numpy 的 all() 方法比較陣列內的元素是否與 digits.data 完全相同：print(np.all(digits.images.reshape((1797,64)) == digits.data))，而我們會得到 True 的結果。

(1797, 64)
(1797,)
(1797, 8, 8)
